project:
  type: website
  output-dir: docs

website:
  favicon: media/CleanShot 2026-03-23 at 17.28.16@2x.png
  navbar:
    search: false # search bar disabled
    left:
      - href: home.qmd
        text: Home
      - href: writings.qmd
        text: Writings
      - text: CV
        href: media/dsk_resume.pdf

format:
  html:
    theme: styles.scss
    mainfont: Lato
    page-layout: full
    include-in-header: 
      text: | 
        <meta name="robots" content="noindex,nofollow"/>




